name: readme code stats

on:
  workflow_dispatch:
  schedule:
    - cron: "20 11 * * *"

jobs:
  update-readme:
    name: readme code stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_TOTAL: true
